name: staticbuilds

on:
    # release:
    #     types: [published]
    # schedule:
    # - cron: "14 13 * * *"
    workflow_dispatch:

env:
  CTEST_PARALLEL_LEVEL: "1"
  CMAKE_BUILD_PARALLEL_LEVEL: "4"

jobs:
  staticbuilds-linux:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: dtolnay/rust-toolchain@1.70
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Prepare
      run: |
           sudo pip3 install --break-system-packages sphinx cargo-zigbuild
           rustup target add x86_64-unknown-linux-musl
           rustup target add aarch64-unknown-linux-musl
           rustup target add x86_64-apple-darwin
           rustup target add aarch64-apple-darwin
           sudo apt install python3-pexpect tmux -y
    - name: Build Linux
      run: |
           cargo zigbuild --release --target x86_64-unknown-linux-musl
    - name: Test
      run: |
           test -e tests/test_driver.py && tests/test_driver.py -f /tmp target/x86_64-unknown-linux-musl/release/
    - name: Build Linux Arm
      run: |
           cargo zigbuild --release --target aarch64-unknown-linux-musl --bin fish
    - name: Build macOS
      run: |
           PCRE2_SYS_STATIC=1 cargo zigbuild --release --target aarch64-apple-darwin --bin fish
           PCRE2_SYS_STATIC=1 cargo zigbuild --release --target x86_64-apple-darwin --bin fish
    - name: Compress
      run: |
           tar -cazf fish-amd64.tar.xz -C target/x86_64-unknown-linux-musl/release/ fish
           tar -cazf fish-aarch64.tar.xz -C target/aarch64-unknown-linux-musl/release/ fish
           tar -cazf fish-macos-aarch64.tar.xz -C target/aarch64-apple-darwin/release/ fish
           tar -cazf fish-macos-amd64.tar.xz -C target/x86_64-apple-darwin/release/ fish
    - uses: actions/upload-artifact@v4
      with:
        name: fish-static-linux
        path: |
              fish-amd64.tar.xz
              fish-aarch64.tar.xz
              fish-macos-amd64.tar.xz
              fish-macos-aarch64.tar.xz
        retention-days: 14
