name: staticbuilds

on: [push, pull_request, workflow_dispatch]

env:
  CTEST_PARALLEL_LEVEL: "1"
  CMAKE_BUILD_PARALLEL_LEVEL: "4"

jobs:
  staticbuilds:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: dtolnay/rust-toolchain@1.70
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Prepare
      run: |
           rustup target add x86_64-unknown-linux-musl
           sudo apt install musl-tools -y

    - name: Build
      run: cargo build -r --target x86_64-unknown-linux-musl
    - name: Compress
           tar -cazf fish.tar.xz -c target/release/ fish{,_indent,_key_reader}
    - uses: actions/upload-artifact@v4
      with:
        name: fish
        path: 'fish.tar.xz'
        retention-days: 14
